# Generated by Django 5.1.2 on 2024-11-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_country_rename_pictureurl_userinfo_avatarurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='avatarURL',
        ),
    ]
